import Navbar from '@/components/Navbar/Navbar'
import type { Metadata } from 'next'
import Footer from '@/components/Footer/Footer'


export const metadata: Metadata = {
  title: 'Jose Luis Vallejos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        {children}
        <Footer />
        </body>
    </html>
  )
}
